### PR TITLE
Differentiate between CLs without reviewers and WIPs

### PR DESCRIPTION
**Pull request by adg**
There should be a distinction between CLs that have been sent out for
review but that do not have assigned reviewers, and those that are
published to Gerrit with the "work in progress" label attached.

This change splits these distinct states into separate categories with
different labels, but they still use the same grey icon as before (now
renamed to "not_ready").

### CODE REVIEW

**Comment by sdefresne** [comment]
Thank you for the changes.

You'll also need to make some changes to src/popup.css to add support for the new class noReviewers and workInProgress, and remove the notMailed class. I guess you can probably copy the rules for notMailed twice, once for noReviewers, the other for workInProgress.

Once this is done, I'll merge the pull request.

**Comment by sdefresne** [comment]
The following should be enough:

`diff --git a/src/popup.css b/src/popup.css
index 75ec212..9793288 100644
--- a/src/popup.css
+++ b/src/popup.css
@@ -64,7 +64,11 @@ table {
   background: #00796b;
 }
 
-.notMailed > .sectionheader {
+.noReviewers > .sectionheader {
+  background: #bdbdbd;
+}
+
+.workInProgress > .sectionheader {
   background: #bdbdbd;
 }
 
@@ -104,8 +108,8 @@ table {
   text-overflow: ellipsis;
 }
 
-.approved .author, .notMailed .author, .outgoingRequiringAttention .author,
-.stale .author {
+.approved .author, .noReviewers .author, .outgoingRequiringAttention .author,
+.stale .author, .workInProgress .author {
   display: none;
 }
 
`

**Comment by adg** [comment]
Done.

**Comment by adg** [comment]
Thanks for the handy extension! =D

**Pull request merged**
